apiVersion: v1
kind: Namespace
metadata:
  name:  ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-controller-nginx
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.5.2
  targetNamespace: ingress-nginx
  # valuesContent: |-
  #   replicas:   